# Basic
name:               "Astro.IQ"
description:        "Machine Learning + Trajectory Optimisation"
google_analytics:   "UA-81308018-1"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "https://cisprague.github.io"
author:             "Christopher Iliffe Sprague"
github:
  username:         "cisprague"

# URL
baseurl:            "/Astro.IQ"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "/Astro.IQ/about"
  - name:           "Download"
    href:           "/Astro.IQ/download"
  - name:           "Tutorials"
    href:           "/Astro.IQ/tutorials"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
